Repository azavea/raster-vision, pull requests merged in 2019-03, with the labels that each got.

#698 Add support for evaluating vector output with AOIs
  docs/changelog.rst
  rastervision/evaluation/semantic_segmentation_evaluation.py
  rastervision/evaluation/semantic_segmentation_evaluator.py
  tests/data-files/1-aoi.geojson
  tests/data-files/expected-vector-eval-with-aoi.json
  tests/evaluation/test_semantic_segmentation_evaluator.py
Labels: review

#701 Predict zero for nodata pixels on semantic segmentation
  docs/changelog.rst
  rastervision/task/semantic_segmentation.py
Labels: review

#708 Fix issue with saving semseg predictions for non-georeferenced imagery
  docs/changelog.rst
  rastervision/data/crs_transformer/crs_transformer.py
  rastervision/data/crs_transformer/rasterio_crs_transformer.py
  rastervision/data/label_store/semantic_segmentation_raster_store.py
Labels: needs-backport, review

#711 Simplify and generalize geom processing
  docs/changelog.rst
  rastervision/data/crs_transformer/crs_transformer.py
  rastervision/data/label/object_detection_labels.py
  rastervision/data/label_source/chip_classification_label_source.py
  rastervision/data/label_source/chip_classification_label_source_config.py
  rastervision/data/label_source/object_detection_geojson_source_config.py
  rastervision/data/label_source/object_detection_label_source.py
  rastervision/data/label_source/object_detection_label_source_config.py
  rastervision/data/label_source/utils.py
  rastervision/data/label_store/chip_classification_geojson_store.py
  rastervision/data/label_store/object_detection_geojson_store.py
  rastervision/data/label_store/utils.py
  rastervision/data/raster_source/rasterized_source.py
  rastervision/data/raster_source/rasterized_source_config.py
  rastervision/data/scene_config.py
  rastervision/data/utils.py
  rastervision/data/vector_source/geojson_vector_source.py
  rastervision/data/vector_source/geojson_vector_source_config.py
  rastervision/data/vector_source/label_maker/filter.py
  rastervision/data/vector_source/vector_source.py
  rastervision/data/vector_source/vector_source_config.py
  rastervision/data/vector_source/vector_tile_vector_source.py
  rastervision/data/vector_source/vector_tile_vector_source_config.py
  rastervision/evaluation/semantic_segmentation_evaluator.py
  rastervision/protos/raster_source.proto
  rastervision/protos/vector_source.proto
  rastervision/protos/vector_source_pb2.py
  rastervision/utils/files.py
  rastervision/utils/geojson.py
  tests/data-files/vector_tiles/lv-mbtiles.json
  tests/data-files/vector_tiles/lv-zxy.json
  tests/data/label_source/test_chip_classification_label_source.py
  tests/data/label_source/test_object_detection_label_source.py
  tests/data/label_store/test_chip_classification_geojson_store.py
  tests/data/label_store/test_object_detection_geojson_store.py
  tests/data/mock_crs_transformer.py
  tests/data/raster_source/test_rasterized_source.py
  tests/data/vector_source/test_geojson_vector_source.py
  tests/data/vector_source/test_vector_tile_vector_source.py
  tests/evaluation/test_semantic_segmentation_evaluator.py
  tests/mock/__init__.py
  tests/mock/rasterized_source.py
Labels: review

#721 Simplify/clarify/test/validate RasterSource
  docs/changelog.rst
  integration_tests/integration_tests.py
  rastervision/data/raster_source/geotiff_source.py
  rastervision/data/raster_source/raster_source.py
  rastervision/data/raster_source/raster_source_config.py
  rastervision/data/raster_source/rasterio_source.py
  rastervision/data/raster_transformer/raster_transformer.py
  rastervision/data/raster_transformer/stats_transformer.py
  rastervision/predictor.py
  tests/data/raster_source/test_geotiff_source.py
  tests/data/raster_source/test_image_source.py
Labels: review

#723 Merge GeoTiffSource and ImageSource into RasterioSource
  docs/changelog.rst
  rastervision/data/label_source/semantic_segmentation_label_source_config.py
  rastervision/data/label_store/semantic_segmentation_raster_store.py
  rastervision/data/raster_source/__init__.py
  rastervision/data/raster_source/api.py
  rastervision/data/raster_source/default.py
  rastervision/data/raster_source/geotiff_source.py
  rastervision/data/raster_source/image_source.py
  rastervision/data/raster_source/image_source_config.py
  rastervision/data/raster_source/rasterio_source.py
  rastervision/data/raster_source/rasterio_source_config.py
  rastervision/protos/raster_source.proto
  rastervision/protos/raster_source_pb2.py
  rastervision/registry.py
  tests/command/test_analyze_command.py
  tests/command/test_bundle_command.py
  tests/command/test_eval_command.py
  tests/data/label_source/test_semantic_segmentation_label_source.py
  tests/data/raster_source/test_image_source.py
  tests/data/raster_source/test_rasterio_source.py
  tests/experiment/test_experiment_loader.py
  tests/task/test_chip_classification.py
Labels: review

#725 Handle Rasterio crs that doesn't contain EPSG
  docs/changelog.rst
  rastervision/data/crs_transformer/rasterio_crs_transformer.py
  tests/data/raster_source/test_rasterio_source.py
Labels: needs-backport, review

#726 Switch default branch to master
  .travis/deploy
  docs/changelog.rst
  docs/release.rst
Labels: review

#729 Update Badges
  README.md
Labels: review

#732 Make RasterioSource the catch-all for default provider
  rastervision/data/raster_source/default.py
  tests/data/raster_source/test_rasterio_source.py
Labels: review

#733 Load null channel_order correctly
  docs/changelog.rst
  rastervision/data/raster_source/raster_source_config.py
  tests/data/raster_source/test_rasterio_source.py
Labels: needs-backport, review

#731 Allow Spaces in `--channel-order` Argument
  rastervision/cli/main.py
Labels: needs-backport

#737 Reference `master` Branch
  .travis.yml
Labels: review

#734 Use Published `mask-to-polygons` Package
  extras_requirements.json
  setup.py
Labels: review
